### ISSUE TITLE
MaltMeshes.py showing error in console

### ISSUE THREAD

**Issue by df-0** [bnpr/Malt#55]
Hi, I'm getting an error in the console (Blender 2.91.0, Windows 10, Malt whatever most recent version at 1 Feb 2021 was, not sure how to check!).

I have the plugin loaded but I'm using EEVEE, haven't even set up any Malt stuff in this scene. This prints repeatedly in the console:

```Traceback (most recent call last):
  File "C:\Users\[USER]\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderMalt\MaltMeshes.py", line 201, in depsgraph_update
    unload_mesh(update.id)
  File "C:\Users\[USER]\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderMalt\MaltMeshes.py", line 189, in unload_mesh
    MESHES[get_mesh_name(object)] = None
  File "C:\Users\[USER]\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderMalt\MaltMeshes.py", line 22, in get_mesh_name
    name = object.type + '_' + object.data.name_full
AttributeError: 'NoneType' object has no attribute 'name_full'```


Hope that's useful. Thanks for your work!

**Comment by pragma37** [comment]
Fixed!
Thank you for the report.
