### ISSUE TITLE
Blender 2.91 freezes when switching to malt in Pop-os

### ISSUE THREAD

**Issue by TahsinTariq** [bnpr/Malt#58]
I have the v1-refactor version, running on Pop-os 20.10
I have to manually kill the blender processes.
Here's the error I get as the UI freezes:

````
Process Process-2:
Traceback (most recent call last):
  File "/home/tahsin/.config/blender/2.91/scripts/addons/BlenderMalt/.MaltPath/Malt/.Dependencies/psutil/_pslinux.py", line 1576, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/tahsin/.config/blender/2.91/scripts/addons/BlenderMalt/.MaltPath/Malt/.Dependencies/psutil/_pslinux.py", line 1992, in nice_set
    return cext_posix.setpriority(self.pid, value)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/work/blender_291/2.91/python/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/work/blender_291/2.91/python/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tahsin/.config/blender/2.91/scripts/addons/BlenderMalt/.MaltPath/Bridge/Server.py", line 153, in main
    psutil.Process(os.getpid()).nice(priority)
  File "/home/tahsin/.config/blender/2.91/scripts/addons/BlenderMalt/.MaltPath/Malt/.Dependencies/psutil/__init__.py", line 724, in nice
    self._proc.nice_set(value)
  File "/home/tahsin/.config/blender/2.91/scripts/addons/BlenderMalt/.MaltPath/Malt/.Dependencies/psutil/_pslinux.py", line 1578, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=6393)
````

**Comment by ScribbleFen** [comment]
I'm also getting freezing when I switch to Malt, on Manjaro Linux.

**Comment by pragma37** [comment]
Thanks for the reports.

I'm currently working on fixing the refactor branch on Linux.
I'll report here when I get it working locally.

**Comment by pragma37** [comment]
The last version works for me on Ubuntu, could you check it?

**Comment by ScribbleFen** [comment]
Okay works for me now, but it does feel very slow, but that might just be my computer rn

**Comment by TahsinTariq** [comment]
As @ScribbleFen said, it works, but feels a bit slow.
I've also had malt break while in looking around the viewport.
Here's the error:
```
Python: Traceback (most recent call last):
  File "/home/tahsin/.config/blender/2.91/scripts/addons/BlenderMalt/MaltRenderEngine.py", line 250, in view_draw
    Bridge.Client_API.render(self.bridge_id, resolution, scene, self.request_scene_update)
  File "/home/tahsin/.config/blender/2.91/scripts/addons/BlenderMalt/.MaltPath/Bridge/Client_API.py", line 129, in render
    'buffer_name': ipc.get_shared_buffer_full_name(name),
  File "/work/blender_291/2.91/python/lib/python3.7/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/work/blender_291/2.91/python/lib/python3.7/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/work/blender_291/2.91/python/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
```

I have to change render engine to eevee and then malt to restart it. And every time a 2nd window pops up.

![image](https://user-images.githubusercontent.com/62146852/108674922-3e4b9780-7510-11eb-9367-7e1974b55659.png)

Also, UI resizing breaks the viewport. Here, I'm trying to resize the properties tab:
![image](https://user-images.githubusercontent.com/62146852/108675293-cf227300-7510-11eb-95a4-a221e25af639.png)

**Comment by pragma37** [comment]
@TahsinTariq Slower than the beta branch?
Keep in mind that the refactor introduces (usually) 2 frames of latency compared to the Blender overlay.

That's not the actual error. That means the Malt process crashed at some point and now it can't connect to it. The actual error happened earlier.
I'm implementing a log system so it's easier to report this kind of info.
And also will add a check so when the Malt process crashes a new one is created.

That window is the process where Malt runs. I could hide it but then the os scheduler gives it lower priority (at least on Windows).
It should start minimized, though. Does it?

That resizing glitch is expected, don't worry too much about it. It doesn't have any side effects but I'll fix it at some point.

**Comment by TahsinTariq** [comment]
I think it felt slow cause I was specifically looking for it to be. 

And Yes, the malt process starts minimized.

> That resizing glitch is expected, don't worry too much about it. It doesn't have any side effects but I'll fix it at some point.
Malt crashed a few times while I was resizing. I don't know if they are related though.

I think we can close this issue for now.
