### ISSUE TITLE
Permission issues when removing addon

### ISSUE THREAD

**Issue by tonpix** [bnpr/Malt#59]
Workaround requires restarting blender to avoid this error message and make addon disappear from list

```
Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\startup\bl_operators\userpref.py", line 793, in execute
    shutil.rmtree(path)
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\lib\shutil.py", line 516, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\lib\shutil.py", line 395, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\lib\shutil.py", line 395, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\lib\shutil.py", line 395, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  [Previous line repeated 1 more time]
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\lib\shutil.py", line 400, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\lib\shutil.py", line 398, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\tonpix\\AppData\\Roaming\\Blender Foundation\\Blender\\2.91\\scripts\\addons\\BlenderMalt\\.MaltPath\\Malt\\.Dependencies\\OpenGL_accelerate\\arraydatatype.cp37-win_amd64.pyd'

location: <unknown location>:-1
```

**Comment by pragma37** [comment]
Hi. Yes, this is a known issue, it's stated in the install instructions https://github.com/bnpr/Malt/#install.

I think there's no way to solve it since, afaik, Python doesn't allow to manually unload dynamic libraries.
