### ISSUE TITLE
AssertionError - assert(i < max_uv)

### ISSUE THREAD

**Issue by Joeboy** [bnpr/Malt#64]
Hi

I got an error when I tried to go into rendered viewport mode, with the "Vincent" blend file available at https://cloud.blender.org/p/characters/5718a967c379cf04929a4247

The error looks like this:
```
Python: Traceback (most recent call last):
  File "/home/joe/.config/blender/2.91/scripts/addons/BlenderMalt/MaltRenderEngine.py", line 283, in view_draw
    scene = self.get_scene(context, depsgraph, self.request_scene_update)
  File "/home/joe/.config/blender/2.91/scripts/addons/BlenderMalt/MaltRenderEngine.py", line 179, in get_scene
    add_object(obj, obj.matrix_world)
  File "/home/joe/.config/blender/2.91/scripts/addons/BlenderMalt/MaltRenderEngine.py", line 108, in add_object
    malt_mesh = MaltMeshes.get_mesh(obj)
  File "/home/joe/.config/blender/2.91/scripts/addons/BlenderMalt/MaltMeshes.py", line 28, in get_mesh
    MESHES[key] = load_mesh(object)
  File "/home/joe/.config/blender/2.91/scripts/addons/BlenderMalt/MaltMeshes.py", line 162, in load_mesh
    assert(i < max_uv)
AssertionError
```

Seems to be caused by multiple UV layers, or something like that (I don't know anything about UV layers).

Not a big problem for me, just thought I'd report it. Maybe it could at least provide a warning when there are multiple UVs.

Thanks!

**Comment by pragma37** [comment]
Hi!

Thank you, I don't know what I was thinking when I wrote that code.
I fixed it on the refactor branch: ddad3dc80621e59f9eec93aa68c786cdc8f89445
Now it just logs a warning instead of failing to load the mesh.

Thank you for the report!
