### ISSUE TITLE
Blender 2.92 freezes when switching to malt in Gentoo Linux

### ISSUE THREAD

**Issue by Zeggpold87** [bnpr/Malt#68]
This happens with the default cube; just install the addon, and then change the renderer to Malt.  It looks like what happens is that malt tries to raise it's priority and fails (because an ordinary user doesn't have permission to do that) and crashes, and then gets restarted repeatedly.  Eventually had to kill the blender.  Extract from the log file (the whole file is attached below):

`Blender > DEBUG MODE: False
Blender > Traceback (most recent call last):
  File "/home/purtill/.config/blender/2.92/scripts/addons/BlenderMalt/.MaltPath/Malt/.Dependencies/psutil/_pslinux.py", line 1576, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/purtill/.config/blender/2.92/scripts/addons/BlenderMalt/.MaltPath/Malt/.Dependencies/psutil/_pslinux.py", line 1992, in nice_set
    return cext_posix.setpriority(self.pid, value)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/purtill/.config/blender/2.92/scripts/addons/BlenderMalt/.MaltPath/Bridge/Server.py", line 219, in main
    psutil.Process().nice(-15)
  File "/home/purtill/.config/blender/2.92/scripts/addons/BlenderMalt/.MaltPath/Malt/.Dependencies/psutil/__init__.py", line 724, in nice
    self._proc.nice_set(value)
  File "/home/purtill/.config/blender/2.92/scripts/addons/BlenderMalt/.MaltPath/Malt/.Dependencies/psutil/_pslinux.py", line 1578, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=4333)
`

[malt 2021-03-15(17-55).log](https://github.com/bnpr/Malt/files/6145886/malt.2021-03-15.17-55.log)

Let me know if you need more information.

**Comment by pragma37** [comment]
I pushed a commit yesterday 146fcacc9be575a9b78a2f26efebbf462d477c13 that should fix this.
Please, try the latest build.

That said, the exception should be cached and handled without problems. Not sure why that's not the case.

**Comment by grantmoore3d** [comment]
Just had the same problem when testing the `v1-refactor` release. Is there somewhere I can access more frequent builds to see if your referenced commit fixed it?

**Comment by pragma37** [comment]
The release section always has the latest build, it's automated.
https://github.com/bnpr/Malt/releases

**Comment by Zeggpold87** [comment]
This is solved in the releases I downloaded on the 17th from the releases page (both the "beta" and "refactor" versions.  Thanks!
