### ISSUE TITLE
Error trying to remove previous version of malt on windows

### ISSUE THREAD

**Issue by TahsinTariq** [bnpr/Malt#69]
Updated from blender 2.91 to 2.92 on windows.

I'm getting this error.
~~~
Unable to load numpy_formathandler accelerator from OpenGL_accelerate
Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\startup\bl_operators\userpref.py", line 793, in execute
    shutil.rmtree(path)
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\python\lib\shutil.py", line 516, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\python\lib\shutil.py", line 395, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\python\lib\shutil.py", line 400, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\python\lib\shutil.py", line 398, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\Tahsin\\AppData\\Roaming\\Blender Foundation\\Blender\\2.92\\scripts\\addons\\BlenderMalt\\CBlenderMalt\\CMalt.dll'

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\startup\bl_operators\userpref.py", line 793, in execute
    shutil.rmtree(path)
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\python\lib\shutil.py", line 516, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\python\lib\shutil.py", line 395, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\python\lib\shutil.py", line 400, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\python\lib\shutil.py", line 398, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\Tahsin\\AppData\\Roaming\\Blender Foundation\\Blender\\2.92\\scripts\\addons\\BlenderMalt\\CBlenderMalt\\CMalt.dll'

location: <unknown location>:-1
~~~

**Comment by TahsinTariq** [comment]
I had to delete the addon folder from AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons and install the newer version of malt

**Comment by pragma37** [comment]
This is stated in the README.
https://github.com/bnpr/Malt#uninstall

You don't have to delete the folder, just disable the addon and reset blender before delete.

Explanation: https://github.com/bnpr/Malt/issues/59#issuecomment-784473052
